version: "3"
services:
  heyheybot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: HeyHeyBot
    environment:
    #   - DISCORD_TOKEN=YOUR_DISCORD_TOKEN
      - DISCORD_RICH_PRESENCE=True
      - DISCORD_MUTING_ANNOUNCE=False
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped